"""
    Nucoro API

    No description  # noqa: E501

    The version of the OpenAPI document: 4.175.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.invoice_list import InvoiceList
globals()['InvoiceList'] = InvoiceList
from openapi_client.model.paginated_invoice_list_list import PaginatedInvoiceListList


class TestPaginatedInvoiceListList(unittest.TestCase):
    """PaginatedInvoiceListList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedInvoiceListList(self):
        """Test PaginatedInvoiceListList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedInvoiceListList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
