"""
    Nucoro API

    No description  # noqa: E501

    The version of the OpenAPI document: 4.175.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.impersonation_token import ImpersonationToken


class TestImpersonationToken(unittest.TestCase):
    """ImpersonationToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImpersonationToken(self):
        """Test ImpersonationToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImpersonationToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
