"""
    Nucoro API

    No description  # noqa: E501

    The version of the OpenAPI document: 4.175.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.bank_account_list import BankAccountList


class TestBankAccountList(unittest.TestCase):
    """BankAccountList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankAccountList(self):
        """Test BankAccountList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BankAccountList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
