"""
    Nucoro API

    No description  # noqa: E501

    The version of the OpenAPI document: 4.175.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.document_type_enum import DocumentTypeEnum
globals()['DocumentTypeEnum'] = DocumentTypeEnum
from openapi_client.model.verification_document import VerificationDocument


class TestVerificationDocument(unittest.TestCase):
    """VerificationDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerificationDocument(self):
        """Test VerificationDocument"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VerificationDocument()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
