"""
    Nucoro API

    No description  # noqa: E501

    The version of the OpenAPI document: 4.175.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.asset_category import AssetCategory


class TestAssetCategory(unittest.TestCase):
    """AssetCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetCategory(self):
        """Test AssetCategory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssetCategory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
