"""
    Nucoro API

    No description  # noqa: E501

    The version of the OpenAPI document: 4.175.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.status_bd7_enum import StatusBd7Enum
from openapi_client.model.verify_type_enum import VerifyTypeEnum
globals()['StatusBd7Enum'] = StatusBd7Enum
globals()['VerifyTypeEnum'] = VerifyTypeEnum
from openapi_client.model.verification_create import VerificationCreate


class TestVerificationCreate(unittest.TestCase):
    """VerificationCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerificationCreate(self):
        """Test VerificationCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VerificationCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
