=begin
Nucoro API

No description

The version of the OpenAPI document: 4.175.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class InvestorFee < ApplicationRecord
  validates_presence_of :fee_type
  validates_presence_of :concept
  validates_presence_of :uuid
  validates_presence_of :created
  validates_presence_of :updated

end
