=begin
Nucoro API

No description

The version of the OpenAPI document: 4.175.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class PortfolioCreate < ApplicationRecord
  validates_presence_of :uuid
  validates_presence_of :name
  validates_presence_of :portfolio_type
  validates_presence_of :risk_level
  validates_presence_of :time_horizon
  validates_presence_of :status
  validates_presence_of :created
  validates_presence_of :activated
  validates_presence_of :advisor
  validates_presence_of :advice_engine

  serialize :extra_data, Hash
end
