=begin
Nucoro API

No description

The version of the OpenAPI document: 4.175.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class Price < ApplicationRecord
  validates_presence_of :amount
  validates_presence_of :datetime
  validates_presence_of :date

end
