<?php
/**
 * PortfolioPerformancePositions
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nucoro API
 *
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PortfolioPerformancePositions Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class PortfolioPerformancePositions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PortfolioPerformancePositions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'valuation_datetime' => '\DateTime',
        'last_update' => '\DateTime',
        'asset' => 'string',
        'shares' => 'double',
        'price' => 'double',
        'currency' => 'string',
        'weight' => 'double',
        'fx_rate_account' => 'double',
        'asset_currency_value' => 'double',
        'value' => 'double',
        'position_return' => 'double',
        'unrealised_pl' => 'double',
        'realised_pl' => 'double',
        'earnings' => 'double',
        'avg_entry_price' => 'double',
        'daily_pl' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'valuation_datetime' => 'date-time',
        'last_update' => 'date-time',
        'asset' => null,
        'shares' => 'double',
        'price' => 'double',
        'currency' => null,
        'weight' => 'double',
        'fx_rate_account' => 'double',
        'asset_currency_value' => 'double',
        'value' => 'double',
        'position_return' => 'double',
        'unrealised_pl' => 'double',
        'realised_pl' => 'double',
        'earnings' => 'double',
        'avg_entry_price' => 'double',
        'daily_pl' => 'double'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'valuation_datetime' => 'valuation_datetime',
        'last_update' => 'last_update',
        'asset' => 'asset',
        'shares' => 'shares',
        'price' => 'price',
        'currency' => 'currency',
        'weight' => 'weight',
        'fx_rate_account' => 'fx_rate_account',
        'asset_currency_value' => 'asset_currency_value',
        'value' => 'value',
        'position_return' => 'position_return',
        'unrealised_pl' => 'unrealised_pl',
        'realised_pl' => 'realised_pl',
        'earnings' => 'earnings',
        'avg_entry_price' => 'avg_entry_price',
        'daily_pl' => 'daily_pl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'valuation_datetime' => 'setValuationDatetime',
        'last_update' => 'setLastUpdate',
        'asset' => 'setAsset',
        'shares' => 'setShares',
        'price' => 'setPrice',
        'currency' => 'setCurrency',
        'weight' => 'setWeight',
        'fx_rate_account' => 'setFxRateAccount',
        'asset_currency_value' => 'setAssetCurrencyValue',
        'value' => 'setValue',
        'position_return' => 'setPositionReturn',
        'unrealised_pl' => 'setUnrealisedPl',
        'realised_pl' => 'setRealisedPl',
        'earnings' => 'setEarnings',
        'avg_entry_price' => 'setAvgEntryPrice',
        'daily_pl' => 'setDailyPl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'valuation_datetime' => 'getValuationDatetime',
        'last_update' => 'getLastUpdate',
        'asset' => 'getAsset',
        'shares' => 'getShares',
        'price' => 'getPrice',
        'currency' => 'getCurrency',
        'weight' => 'getWeight',
        'fx_rate_account' => 'getFxRateAccount',
        'asset_currency_value' => 'getAssetCurrencyValue',
        'value' => 'getValue',
        'position_return' => 'getPositionReturn',
        'unrealised_pl' => 'getUnrealisedPl',
        'realised_pl' => 'getRealisedPl',
        'earnings' => 'getEarnings',
        'avg_entry_price' => 'getAvgEntryPrice',
        'daily_pl' => 'getDailyPl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['valuation_datetime'] = $data['valuation_datetime'] ?? null;
        $this->container['last_update'] = $data['last_update'] ?? null;
        $this->container['asset'] = $data['asset'] ?? null;
        $this->container['shares'] = $data['shares'] ?? null;
        $this->container['price'] = $data['price'] ?? null;
        $this->container['currency'] = $data['currency'] ?? null;
        $this->container['weight'] = $data['weight'] ?? null;
        $this->container['fx_rate_account'] = $data['fx_rate_account'] ?? null;
        $this->container['asset_currency_value'] = $data['asset_currency_value'] ?? null;
        $this->container['value'] = $data['value'] ?? null;
        $this->container['position_return'] = $data['position_return'] ?? null;
        $this->container['unrealised_pl'] = $data['unrealised_pl'] ?? null;
        $this->container['realised_pl'] = $data['realised_pl'] ?? null;
        $this->container['earnings'] = $data['earnings'] ?? null;
        $this->container['avg_entry_price'] = $data['avg_entry_price'] ?? null;
        $this->container['daily_pl'] = $data['daily_pl'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['valuation_datetime'] === null) {
            $invalidProperties[] = "'valuation_datetime' can't be null";
        }
        if ($this->container['last_update'] === null) {
            $invalidProperties[] = "'last_update' can't be null";
        }
        if ($this->container['asset'] === null) {
            $invalidProperties[] = "'asset' can't be null";
        }
        if ($this->container['shares'] === null) {
            $invalidProperties[] = "'shares' can't be null";
        }
        if (($this->container['shares'] > 1000000000000)) {
            $invalidProperties[] = "invalid value for 'shares', must be smaller than or equal to 1000000000000.";
        }

        if (($this->container['shares'] < -1000000000000)) {
            $invalidProperties[] = "invalid value for 'shares', must be bigger than or equal to -1000000000000.";
        }

        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }
        if (($this->container['price'] > 1000000000000)) {
            $invalidProperties[] = "invalid value for 'price', must be smaller than or equal to 1000000000000.";
        }

        if (($this->container['price'] < -1000000000000)) {
            $invalidProperties[] = "invalid value for 'price', must be bigger than or equal to -1000000000000.";
        }

        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        if (!is_null($this->container['weight']) && ($this->container['weight'] > 1000000000000)) {
            $invalidProperties[] = "invalid value for 'weight', must be smaller than or equal to 1000000000000.";
        }

        if (!is_null($this->container['weight']) && ($this->container['weight'] < -1000000000000)) {
            $invalidProperties[] = "invalid value for 'weight', must be bigger than or equal to -1000000000000.";
        }

        if (!is_null($this->container['fx_rate_account']) && ($this->container['fx_rate_account'] > 1000000000000)) {
            $invalidProperties[] = "invalid value for 'fx_rate_account', must be smaller than or equal to 1000000000000.";
        }

        if (!is_null($this->container['fx_rate_account']) && ($this->container['fx_rate_account'] < -1000000000000)) {
            $invalidProperties[] = "invalid value for 'fx_rate_account', must be bigger than or equal to -1000000000000.";
        }

        if (!is_null($this->container['asset_currency_value']) && ($this->container['asset_currency_value'] > 1000000000000)) {
            $invalidProperties[] = "invalid value for 'asset_currency_value', must be smaller than or equal to 1000000000000.";
        }

        if (!is_null($this->container['asset_currency_value']) && ($this->container['asset_currency_value'] < -1000000000000)) {
            $invalidProperties[] = "invalid value for 'asset_currency_value', must be bigger than or equal to -1000000000000.";
        }

        if ($this->container['value'] === null) {
            $invalidProperties[] = "'value' can't be null";
        }
        if (($this->container['value'] > 1000000000000)) {
            $invalidProperties[] = "invalid value for 'value', must be smaller than or equal to 1000000000000.";
        }

        if (($this->container['value'] < -1000000000000)) {
            $invalidProperties[] = "invalid value for 'value', must be bigger than or equal to -1000000000000.";
        }

        if ($this->container['position_return'] === null) {
            $invalidProperties[] = "'position_return' can't be null";
        }
        if (($this->container['position_return'] > 1000000000000)) {
            $invalidProperties[] = "invalid value for 'position_return', must be smaller than or equal to 1000000000000.";
        }

        if (($this->container['position_return'] < -1000000000000)) {
            $invalidProperties[] = "invalid value for 'position_return', must be bigger than or equal to -1000000000000.";
        }

        if ($this->container['unrealised_pl'] === null) {
            $invalidProperties[] = "'unrealised_pl' can't be null";
        }
        if (($this->container['unrealised_pl'] > 1000000000000)) {
            $invalidProperties[] = "invalid value for 'unrealised_pl', must be smaller than or equal to 1000000000000.";
        }

        if (($this->container['unrealised_pl'] < -1000000000000)) {
            $invalidProperties[] = "invalid value for 'unrealised_pl', must be bigger than or equal to -1000000000000.";
        }

        if ($this->container['realised_pl'] === null) {
            $invalidProperties[] = "'realised_pl' can't be null";
        }
        if (($this->container['realised_pl'] > 1000000000000)) {
            $invalidProperties[] = "invalid value for 'realised_pl', must be smaller than or equal to 1000000000000.";
        }

        if (($this->container['realised_pl'] < -1000000000000)) {
            $invalidProperties[] = "invalid value for 'realised_pl', must be bigger than or equal to -1000000000000.";
        }

        if ($this->container['earnings'] === null) {
            $invalidProperties[] = "'earnings' can't be null";
        }
        if (($this->container['earnings'] > 1000000000000)) {
            $invalidProperties[] = "invalid value for 'earnings', must be smaller than or equal to 1000000000000.";
        }

        if (($this->container['earnings'] < -1000000000000)) {
            $invalidProperties[] = "invalid value for 'earnings', must be bigger than or equal to -1000000000000.";
        }

        if ($this->container['avg_entry_price'] === null) {
            $invalidProperties[] = "'avg_entry_price' can't be null";
        }
        if (($this->container['avg_entry_price'] > 1000000000000)) {
            $invalidProperties[] = "invalid value for 'avg_entry_price', must be smaller than or equal to 1000000000000.";
        }

        if (($this->container['avg_entry_price'] < -1000000000000)) {
            $invalidProperties[] = "invalid value for 'avg_entry_price', must be bigger than or equal to -1000000000000.";
        }

        if ($this->container['daily_pl'] === null) {
            $invalidProperties[] = "'daily_pl' can't be null";
        }
        if (($this->container['daily_pl'] > 1000000000000)) {
            $invalidProperties[] = "invalid value for 'daily_pl', must be smaller than or equal to 1000000000000.";
        }

        if (($this->container['daily_pl'] < -1000000000000)) {
            $invalidProperties[] = "invalid value for 'daily_pl', must be bigger than or equal to -1000000000000.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets valuation_datetime
     *
     * @return \DateTime
     */
    public function getValuationDatetime()
    {
        return $this->container['valuation_datetime'];
    }

    /**
     * Sets valuation_datetime
     *
     * @param \DateTime $valuation_datetime valuation_datetime
     *
     * @return self
     */
    public function setValuationDatetime($valuation_datetime)
    {
        $this->container['valuation_datetime'] = $valuation_datetime;

        return $this;
    }

    /**
     * Gets last_update
     *
     * @return \DateTime
     */
    public function getLastUpdate()
    {
        return $this->container['last_update'];
    }

    /**
     * Sets last_update
     *
     * @param \DateTime $last_update last_update
     *
     * @return self
     */
    public function setLastUpdate($last_update)
    {
        $this->container['last_update'] = $last_update;

        return $this;
    }

    /**
     * Gets asset
     *
     * @return string
     */
    public function getAsset()
    {
        return $this->container['asset'];
    }

    /**
     * Sets asset
     *
     * @param string $asset asset
     *
     * @return self
     */
    public function setAsset($asset)
    {
        $this->container['asset'] = $asset;

        return $this;
    }

    /**
     * Gets shares
     *
     * @return double
     */
    public function getShares()
    {
        return $this->container['shares'];
    }

    /**
     * Sets shares
     *
     * @param double $shares shares
     *
     * @return self
     */
    public function setShares($shares)
    {

        if (($shares > 1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $shares when calling PortfolioPerformancePositions., must be smaller than or equal to 1000000000000.');
        }
        if (($shares < -1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $shares when calling PortfolioPerformancePositions., must be bigger than or equal to -1000000000000.');
        }

        $this->container['shares'] = $shares;

        return $this;
    }

    /**
     * Gets price
     *
     * @return double
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param double $price price
     *
     * @return self
     */
    public function setPrice($price)
    {

        if (($price > 1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $price when calling PortfolioPerformancePositions., must be smaller than or equal to 1000000000000.');
        }
        if (($price < -1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $price when calling PortfolioPerformancePositions., must be bigger than or equal to -1000000000000.');
        }

        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets weight
     *
     * @return double|null
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param double|null $weight weight
     *
     * @return self
     */
    public function setWeight($weight)
    {

        if (!is_null($weight) && ($weight > 1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $weight when calling PortfolioPerformancePositions., must be smaller than or equal to 1000000000000.');
        }
        if (!is_null($weight) && ($weight < -1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $weight when calling PortfolioPerformancePositions., must be bigger than or equal to -1000000000000.');
        }

        $this->container['weight'] = $weight;

        return $this;
    }

    /**
     * Gets fx_rate_account
     *
     * @return double|null
     */
    public function getFxRateAccount()
    {
        return $this->container['fx_rate_account'];
    }

    /**
     * Sets fx_rate_account
     *
     * @param double|null $fx_rate_account fx_rate_account
     *
     * @return self
     */
    public function setFxRateAccount($fx_rate_account)
    {

        if (!is_null($fx_rate_account) && ($fx_rate_account > 1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $fx_rate_account when calling PortfolioPerformancePositions., must be smaller than or equal to 1000000000000.');
        }
        if (!is_null($fx_rate_account) && ($fx_rate_account < -1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $fx_rate_account when calling PortfolioPerformancePositions., must be bigger than or equal to -1000000000000.');
        }

        $this->container['fx_rate_account'] = $fx_rate_account;

        return $this;
    }

    /**
     * Gets asset_currency_value
     *
     * @return double|null
     */
    public function getAssetCurrencyValue()
    {
        return $this->container['asset_currency_value'];
    }

    /**
     * Sets asset_currency_value
     *
     * @param double|null $asset_currency_value asset_currency_value
     *
     * @return self
     */
    public function setAssetCurrencyValue($asset_currency_value)
    {

        if (!is_null($asset_currency_value) && ($asset_currency_value > 1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $asset_currency_value when calling PortfolioPerformancePositions., must be smaller than or equal to 1000000000000.');
        }
        if (!is_null($asset_currency_value) && ($asset_currency_value < -1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $asset_currency_value when calling PortfolioPerformancePositions., must be bigger than or equal to -1000000000000.');
        }

        $this->container['asset_currency_value'] = $asset_currency_value;

        return $this;
    }

    /**
     * Gets value
     *
     * @return double
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param double $value value
     *
     * @return self
     */
    public function setValue($value)
    {

        if (($value > 1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $value when calling PortfolioPerformancePositions., must be smaller than or equal to 1000000000000.');
        }
        if (($value < -1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $value when calling PortfolioPerformancePositions., must be bigger than or equal to -1000000000000.');
        }

        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets position_return
     *
     * @return double
     */
    public function getPositionReturn()
    {
        return $this->container['position_return'];
    }

    /**
     * Sets position_return
     *
     * @param double $position_return position_return
     *
     * @return self
     */
    public function setPositionReturn($position_return)
    {

        if (($position_return > 1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $position_return when calling PortfolioPerformancePositions., must be smaller than or equal to 1000000000000.');
        }
        if (($position_return < -1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $position_return when calling PortfolioPerformancePositions., must be bigger than or equal to -1000000000000.');
        }

        $this->container['position_return'] = $position_return;

        return $this;
    }

    /**
     * Gets unrealised_pl
     *
     * @return double
     */
    public function getUnrealisedPl()
    {
        return $this->container['unrealised_pl'];
    }

    /**
     * Sets unrealised_pl
     *
     * @param double $unrealised_pl unrealised_pl
     *
     * @return self
     */
    public function setUnrealisedPl($unrealised_pl)
    {

        if (($unrealised_pl > 1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $unrealised_pl when calling PortfolioPerformancePositions., must be smaller than or equal to 1000000000000.');
        }
        if (($unrealised_pl < -1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $unrealised_pl when calling PortfolioPerformancePositions., must be bigger than or equal to -1000000000000.');
        }

        $this->container['unrealised_pl'] = $unrealised_pl;

        return $this;
    }

    /**
     * Gets realised_pl
     *
     * @return double
     */
    public function getRealisedPl()
    {
        return $this->container['realised_pl'];
    }

    /**
     * Sets realised_pl
     *
     * @param double $realised_pl realised_pl
     *
     * @return self
     */
    public function setRealisedPl($realised_pl)
    {

        if (($realised_pl > 1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $realised_pl when calling PortfolioPerformancePositions., must be smaller than or equal to 1000000000000.');
        }
        if (($realised_pl < -1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $realised_pl when calling PortfolioPerformancePositions., must be bigger than or equal to -1000000000000.');
        }

        $this->container['realised_pl'] = $realised_pl;

        return $this;
    }

    /**
     * Gets earnings
     *
     * @return double
     */
    public function getEarnings()
    {
        return $this->container['earnings'];
    }

    /**
     * Sets earnings
     *
     * @param double $earnings earnings
     *
     * @return self
     */
    public function setEarnings($earnings)
    {

        if (($earnings > 1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $earnings when calling PortfolioPerformancePositions., must be smaller than or equal to 1000000000000.');
        }
        if (($earnings < -1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $earnings when calling PortfolioPerformancePositions., must be bigger than or equal to -1000000000000.');
        }

        $this->container['earnings'] = $earnings;

        return $this;
    }

    /**
     * Gets avg_entry_price
     *
     * @return double
     */
    public function getAvgEntryPrice()
    {
        return $this->container['avg_entry_price'];
    }

    /**
     * Sets avg_entry_price
     *
     * @param double $avg_entry_price avg_entry_price
     *
     * @return self
     */
    public function setAvgEntryPrice($avg_entry_price)
    {

        if (($avg_entry_price > 1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $avg_entry_price when calling PortfolioPerformancePositions., must be smaller than or equal to 1000000000000.');
        }
        if (($avg_entry_price < -1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $avg_entry_price when calling PortfolioPerformancePositions., must be bigger than or equal to -1000000000000.');
        }

        $this->container['avg_entry_price'] = $avg_entry_price;

        return $this;
    }

    /**
     * Gets daily_pl
     *
     * @return double
     */
    public function getDailyPl()
    {
        return $this->container['daily_pl'];
    }

    /**
     * Sets daily_pl
     *
     * @param double $daily_pl daily_pl
     *
     * @return self
     */
    public function setDailyPl($daily_pl)
    {

        if (($daily_pl > 1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $daily_pl when calling PortfolioPerformancePositions., must be smaller than or equal to 1000000000000.');
        }
        if (($daily_pl < -1000000000000)) {
            throw new \InvalidArgumentException('invalid value for $daily_pl when calling PortfolioPerformancePositions., must be bigger than or equal to -1000000000000.');
        }

        $this->container['daily_pl'] = $daily_pl;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


