/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AssetTypeEnum.
* @enum {}
* @readonly
*/
export default class AssetTypeEnum {
    
        /**
         * value: "ETF"
         * @const
         */
        "ETF" = "ETF";

    
        /**
         * value: "MUTUAL_FUND"
         * @const
         */
        "MUTUAL_FUND" = "MUTUAL_FUND";

    
        /**
         * value: "STOCK"
         * @const
         */
        "STOCK" = "STOCK";

    

    /**
    * Returns a <code>AssetTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AssetTypeEnum} The enum <code>AssetTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

