/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RelatedAssetSerializerWithAssetCategories from './RelatedAssetSerializerWithAssetCategories';

/**
 * The AssetModelPortfolio model module.
 * @module model/AssetModelPortfolio
 * @version 4.175.0
 */
class AssetModelPortfolio {
    /**
     * Constructs a new <code>AssetModelPortfolio</code>.
     * A ModelSerializer that takes additional arguments for \&quot;fields\&quot;, \&quot;omit\&quot; and \&quot;expand\&quot; in order to control which fields are displayed, and whether to replace simple values with complex, nested serializations
     * @alias module:model/AssetModelPortfolio
     * @param asset {module:model/RelatedAssetSerializerWithAssetCategories} 
     * @param weight {Number} 
     */
    constructor(asset, weight) { 
        
        AssetModelPortfolio.initialize(this, asset, weight);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, asset, weight) { 
        obj['asset'] = asset;
        obj['weight'] = weight;
    }

    /**
     * Constructs a <code>AssetModelPortfolio</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetModelPortfolio} obj Optional instance to populate.
     * @return {module:model/AssetModelPortfolio} The populated <code>AssetModelPortfolio</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetModelPortfolio();

            if (data.hasOwnProperty('asset')) {
                obj['asset'] = RelatedAssetSerializerWithAssetCategories.constructFromObject(data['asset']);
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RelatedAssetSerializerWithAssetCategories} asset
 */
AssetModelPortfolio.prototype['asset'] = undefined;

/**
 * @member {Number} weight
 */
AssetModelPortfolio.prototype['weight'] = undefined;






export default AssetModelPortfolio;

