/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AUMEvoluation model module.
 * @module model/AUMEvoluation
 * @version 4.175.0
 */
class AUMEvoluation {
    /**
     * Constructs a new <code>AUMEvoluation</code>.
     * @alias module:model/AUMEvoluation
     * @param valuationDate {Date} 
     * @param balance {Number} 
     */
    constructor(valuationDate, balance) { 
        
        AUMEvoluation.initialize(this, valuationDate, balance);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, valuationDate, balance) { 
        obj['valuation_date'] = valuationDate;
        obj['balance'] = balance;
    }

    /**
     * Constructs a <code>AUMEvoluation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AUMEvoluation} obj Optional instance to populate.
     * @return {module:model/AUMEvoluation} The populated <code>AUMEvoluation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AUMEvoluation();

            if (data.hasOwnProperty('valuation_date')) {
                obj['valuation_date'] = ApiClient.convertToType(data['valuation_date'], 'Date');
            }
            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} valuation_date
 */
AUMEvoluation.prototype['valuation_date'] = undefined;

/**
 * @member {Number} balance
 */
AUMEvoluation.prototype['balance'] = undefined;






export default AUMEvoluation;

