/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BasePortfolioTypeRestrictions model module.
 * @module model/BasePortfolioTypeRestrictions
 * @version 4.175.0
 */
class BasePortfolioTypeRestrictions {
    /**
     * Constructs a new <code>BasePortfolioTypeRestrictions</code>.
     * @alias module:model/BasePortfolioTypeRestrictions
     * @param key {String} 
     * @param dateFrom {Date} 
     * @param dateTo {Date} 
     * @param cleanValue {Number} 
     */
    constructor(key, dateFrom, dateTo, cleanValue) { 
        
        BasePortfolioTypeRestrictions.initialize(this, key, dateFrom, dateTo, cleanValue);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key, dateFrom, dateTo, cleanValue) { 
        obj['key'] = key;
        obj['date_from'] = dateFrom;
        obj['date_to'] = dateTo;
        obj['clean_value'] = cleanValue;
    }

    /**
     * Constructs a <code>BasePortfolioTypeRestrictions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BasePortfolioTypeRestrictions} obj Optional instance to populate.
     * @return {module:model/BasePortfolioTypeRestrictions} The populated <code>BasePortfolioTypeRestrictions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BasePortfolioTypeRestrictions();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('date_from')) {
                obj['date_from'] = ApiClient.convertToType(data['date_from'], 'Date');
            }
            if (data.hasOwnProperty('date_to')) {
                obj['date_to'] = ApiClient.convertToType(data['date_to'], 'Date');
            }
            if (data.hasOwnProperty('clean_value')) {
                obj['clean_value'] = ApiClient.convertToType(data['clean_value'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} key
 */
BasePortfolioTypeRestrictions.prototype['key'] = undefined;

/**
 * @member {Date} date_from
 */
BasePortfolioTypeRestrictions.prototype['date_from'] = undefined;

/**
 * @member {Date} date_to
 */
BasePortfolioTypeRestrictions.prototype['date_to'] = undefined;

/**
 * @member {Number} clean_value
 */
BasePortfolioTypeRestrictions.prototype['clean_value'] = undefined;






export default BasePortfolioTypeRestrictions;

