/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Message from './Message';

/**
 * The ConversationList model module.
 * @module model/ConversationList
 * @version 4.175.0
 */
class ConversationList {
    /**
     * Constructs a new <code>ConversationList</code>.
     * @alias module:model/ConversationList
     * @param uuid {String} 
     * @param created {Date} 
     * @param subject {String} 
     * @param lastMessage {module:model/Message} 
     * @param unreads {Number} 
     */
    constructor(uuid, created, subject, lastMessage, unreads) { 
        
        ConversationList.initialize(this, uuid, created, subject, lastMessage, unreads);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uuid, created, subject, lastMessage, unreads) { 
        obj['uuid'] = uuid;
        obj['created'] = created;
        obj['subject'] = subject;
        obj['last_message'] = lastMessage;
        obj['unreads'] = unreads;
    }

    /**
     * Constructs a <code>ConversationList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConversationList} obj Optional instance to populate.
     * @return {module:model/ConversationList} The populated <code>ConversationList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConversationList();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('last_message')) {
                obj['last_message'] = Message.constructFromObject(data['last_message']);
            }
            if (data.hasOwnProperty('unreads')) {
                obj['unreads'] = ApiClient.convertToType(data['unreads'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} uuid
 */
ConversationList.prototype['uuid'] = undefined;

/**
 * @member {Date} created
 */
ConversationList.prototype['created'] = undefined;

/**
 * @member {String} subject
 */
ConversationList.prototype['subject'] = undefined;

/**
 * @member {module:model/Message} last_message
 */
ConversationList.prototype['last_message'] = undefined;

/**
 * @member {Number} unreads
 */
ConversationList.prototype['unreads'] = undefined;






export default ConversationList;

