/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NationalityList model module.
 * @module model/NationalityList
 * @version 4.175.0
 */
class NationalityList {
    /**
     * Constructs a new <code>NationalityList</code>.
     * A ModelSerializer that takes additional arguments for \&quot;fields\&quot;, \&quot;omit\&quot; and \&quot;expand\&quot; in order to control which fields are displayed, and whether to replace simple values with complex, nested serializations
     * @alias module:model/NationalityList
     * @param uuid {String} 
     * @param country {String} 
     * @param documentNumber {String} 
     */
    constructor(uuid, country, documentNumber) { 
        
        NationalityList.initialize(this, uuid, country, documentNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uuid, country, documentNumber) { 
        obj['uuid'] = uuid;
        obj['country'] = country;
        obj['document_number'] = documentNumber;
    }

    /**
     * Constructs a <code>NationalityList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NationalityList} obj Optional instance to populate.
     * @return {module:model/NationalityList} The populated <code>NationalityList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NationalityList();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('document_type')) {
                obj['document_type'] = ApiClient.convertToType(data['document_type'], 'String');
            }
            if (data.hasOwnProperty('document_number')) {
                obj['document_number'] = ApiClient.convertToType(data['document_number'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} uuid
 */
NationalityList.prototype['uuid'] = undefined;

/**
 * @member {String} country
 */
NationalityList.prototype['country'] = undefined;

/**
 * @member {String} document_type
 */
NationalityList.prototype['document_type'] = undefined;

/**
 * @member {String} document_number
 */
NationalityList.prototype['document_number'] = undefined;






export default NationalityList;

