/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchedNationalityUpdate model module.
 * @module model/PatchedNationalityUpdate
 * @version 4.175.0
 */
class PatchedNationalityUpdate {
    /**
     * Constructs a new <code>PatchedNationalityUpdate</code>.
     * A ModelSerializer that takes additional arguments for \&quot;fields\&quot;, \&quot;omit\&quot; and \&quot;expand\&quot; in order to control which fields are displayed, and whether to replace simple values with complex, nested serializations
     * @alias module:model/PatchedNationalityUpdate
     */
    constructor() { 
        
        PatchedNationalityUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchedNationalityUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchedNationalityUpdate} obj Optional instance to populate.
     * @return {module:model/PatchedNationalityUpdate} The populated <code>PatchedNationalityUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedNationalityUpdate();

            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('document_number')) {
                obj['document_number'] = ApiClient.convertToType(data['document_number'], 'String');
            }
            if (data.hasOwnProperty('document_type')) {
                obj['document_type'] = ApiClient.convertToType(data['document_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} country
 */
PatchedNationalityUpdate.prototype['country'] = undefined;

/**
 * @member {String} document_number
 */
PatchedNationalityUpdate.prototype['document_number'] = undefined;

/**
 * @member {String} document_type
 */
PatchedNationalityUpdate.prototype['document_type'] = undefined;






export default PatchedNationalityUpdate;

