/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ResultEnum.
* @enum {}
* @readonly
*/
export default class ResultEnum {
    
        /**
         * value: "ACCEPTED"
         * @const
         */
        "ACCEPTED" = "ACCEPTED";

    
        /**
         * value: "REJECTED"
         * @const
         */
        "REJECTED" = "REJECTED";

    
        /**
         * value: "DOUBT"
         * @const
         */
        "DOUBT" = "DOUBT";

    

    /**
    * Returns a <code>ResultEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ResultEnum} The enum <code>ResultEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

