/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class StatusB6aEnum.
* @enum {}
* @readonly
*/
export default class StatusB6aEnum {
    
        /**
         * value: "PENDING"
         * @const
         */
        "PENDING" = "PENDING";

    
        /**
         * value: "REQUESTED"
         * @const
         */
        "REQUESTED" = "REQUESTED";

    
        /**
         * value: "PROCESSING"
         * @const
         */
        "PROCESSING" = "PROCESSING";

    
        /**
         * value: "COMPLETED"
         * @const
         */
        "COMPLETED" = "COMPLETED";

    
        /**
         * value: "ERROR"
         * @const
         */
        "ERROR" = "ERROR";

    
        /**
         * value: "CANCELLED"
         * @const
         */
        "CANCELLED" = "CANCELLED";

    

    /**
    * Returns a <code>StatusB6aEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/StatusB6aEnum} The enum <code>StatusB6aEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

