/**
 * Nucoro API v2
 *
 * No description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Message

import com.squareup.moshi.Json

/**
 * 
 *
 * @param uuid 
 * @param created 
 * @param subject 
 * @param lastMessage 
 * @param unreads 
 */

data class ConversationList (

    @Json(name = "uuid")
    val uuid: java.util.UUID,

    @Json(name = "created")
    val created: java.time.OffsetDateTime,

    @Json(name = "subject")
    val subject: kotlin.String,

    @Json(name = "last_message")
    val lastMessage: Message,

    @Json(name = "unreads")
    val unreads: kotlin.Int

)

