/**
 * Nucoro API v2
 *
 * No description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Status2efEnum

import com.squareup.moshi.Json

/**
 * A ModelSerializer that takes additional arguments for \"fields\", \"omit\" and \"expand\" in order to control which fields are displayed, and whether to replace simple values with complex, nested serializations
 *
 * @param uuid 
 * @param name 
 * @param portfolioType 
 * @param created 
 * @param balance 
 * @param performance 
 * @param depositReference 
 * @param riskLevel 
 * @param timeHorizon 
 * @param status 
 * @param extraData Additional Portfolio attributes
 * @param currency 
 * @param activated 
 * @param advisor 
 * @param adviceEngine 
 */

data class PortfolioDetail (

    @Json(name = "uuid")
    val uuid: java.util.UUID,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "portfolio_type")
    val portfolioType: kotlin.String,

    @Json(name = "created")
    val created: java.time.OffsetDateTime,

    @Json(name = "balance")
    val balance: kotlin.Double,

    @Json(name = "performance")
    val performance: kotlin.Double,

    @Json(name = "deposit_reference")
    val depositReference: kotlin.String,

    @Json(name = "risk_level")
    val riskLevel: kotlin.Int? = null,

    @Json(name = "time_horizon")
    val timeHorizon: kotlin.Int? = null,

    @Json(name = "status")
    val status: Status2efEnum? = null,

    /* Additional Portfolio attributes */
    @Json(name = "extra_data")
    val extraData: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "currency")
    val currency: kotlin.String? = null,

    @Json(name = "activated")
    val activated: java.time.OffsetDateTime? = null,

    @Json(name = "advisor")
    val advisor: kotlin.String? = null,

    @Json(name = "advice_engine")
    val adviceEngine: kotlin.String? = null

)

