/**
 * Nucoro API v2
 *
 * No description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Allow get asset by multiple params or UUID
 *
 * @param uuid 
 * @param isin 
 * @param ticker 
 * @param name 
 * @param categories 
 * @param market 
 * @param currency 
 * @param extraData 
 */

data class RelatedAssetSerializerWithAssetCategories (

    @Json(name = "uuid")
    val uuid: java.util.UUID,

    @Json(name = "isin")
    val isin: kotlin.String,

    @Json(name = "ticker")
    val ticker: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "categories")
    val categories: kotlin.collections.List<kotlin.String>,

    @Json(name = "market")
    val market: kotlin.String? = null,

    @Json(name = "currency")
    val currency: kotlin.String? = null,

    @Json(name = "extra_data")
    val extraData: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

