/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NucoroApi);
  }
}(this, function(expect, NucoroApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NucoroApi.KYCApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('KYCApi', function() {
    describe('clientVerificationCreate', function() {
      it('should call clientVerificationCreate successfully', function(done) {
        //uncomment below and update the code to test clientVerificationCreate
        //instance.clientVerificationCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientVerificationDocumentCreate', function() {
      it('should call clientVerificationDocumentCreate successfully', function(done) {
        //uncomment below and update the code to test clientVerificationDocumentCreate
        //instance.clientVerificationDocumentCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientVerificationDocumentDelete', function() {
      it('should call clientVerificationDocumentDelete successfully', function(done) {
        //uncomment below and update the code to test clientVerificationDocumentDelete
        //instance.clientVerificationDocumentDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientVerificationDocumentList', function() {
      it('should call clientVerificationDocumentList successfully', function(done) {
        //uncomment below and update the code to test clientVerificationDocumentList
        //instance.clientVerificationDocumentList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientVerificationDocumentPartialUpdate', function() {
      it('should call clientVerificationDocumentPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test clientVerificationDocumentPartialUpdate
        //instance.clientVerificationDocumentPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientVerificationDocumentRetrieve', function() {
      it('should call clientVerificationDocumentRetrieve successfully', function(done) {
        //uncomment below and update the code to test clientVerificationDocumentRetrieve
        //instance.clientVerificationDocumentRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientVerificationDocumentUpdate', function() {
      it('should call clientVerificationDocumentUpdate successfully', function(done) {
        //uncomment below and update the code to test clientVerificationDocumentUpdate
        //instance.clientVerificationDocumentUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientVerificationList', function() {
      it('should call clientVerificationList successfully', function(done) {
        //uncomment below and update the code to test clientVerificationList
        //instance.clientVerificationList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientVerificationRetrieve', function() {
      it('should call clientVerificationRetrieve successfully', function(done) {
        //uncomment below and update the code to test clientVerificationRetrieve
        //instance.clientVerificationRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
