/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NucoroApi);
  }
}(this, function(expect, NucoroApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NucoroApi.NationlityApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NationlityApi', function() {
    describe('clientNationalityCreate', function() {
      it('should call clientNationalityCreate successfully', function(done) {
        //uncomment below and update the code to test clientNationalityCreate
        //instance.clientNationalityCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientNationlitiesList', function() {
      it('should call clientNationlitiesList successfully', function(done) {
        //uncomment below and update the code to test clientNationlitiesList
        //instance.clientNationlitiesList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientNationlityDelete', function() {
      it('should call clientNationlityDelete successfully', function(done) {
        //uncomment below and update the code to test clientNationlityDelete
        //instance.clientNationlityDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientNationlityPartialUpdate', function() {
      it('should call clientNationlityPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test clientNationlityPartialUpdate
        //instance.clientNationlityPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientNationlityRetrieve', function() {
      it('should call clientNationlityRetrieve successfully', function(done) {
        //uncomment below and update the code to test clientNationlityRetrieve
        //instance.clientNationlityRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('clientNationlityUpdate', function() {
      it('should call clientNationlityUpdate successfully', function(done) {
        //uncomment below and update the code to test clientNationlityUpdate
        //instance.clientNationlityUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
