/**
 * Nucoro API
 *
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AssessmentStatusEnum
import org.openapitools.client.models.RiskChoiceQuestionCode

import com.squareup.moshi.Json

/**
 * 
 *
 * @param uuid 
 * @param choices 
 * @param riskLevel 
 * @param created 
 * @param completed 
 * @param status 
 */

data class Assessment (

    @Json(name = "uuid")
    val uuid: java.util.UUID,

    @Json(name = "choices")
    val choices: kotlin.collections.List<RiskChoiceQuestionCode>,

    @Json(name = "risk_level")
    val riskLevel: kotlin.Int,

    @Json(name = "created")
    val created: java.time.OffsetDateTime,

    @Json(name = "completed")
    val completed: java.time.OffsetDateTime? = null,

    @Json(name = "status")
    val status: AssessmentStatusEnum? = null

)

