/**
 * Nucoro API
 *
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: pENDING,wAITINGFORPRICE,pROCESSING,qUOTED,cOMPLETED,vERIFIED,eRROR,cANCELLED
 */

enum class OrderListStatusEnum(val value: kotlin.String) {

    @Json(name = "PENDING")
    pENDING("PENDING"),

    @Json(name = "WAITING_FOR_PRICE")
    wAITINGFORPRICE("WAITING_FOR_PRICE"),

    @Json(name = "PROCESSING")
    pROCESSING("PROCESSING"),

    @Json(name = "QUOTED")
    qUOTED("QUOTED"),

    @Json(name = "COMPLETED")
    cOMPLETED("COMPLETED"),

    @Json(name = "VERIFIED")
    vERIFIED("VERIFIED"),

    @Json(name = "ERROR")
    eRROR("ERROR"),

    @Json(name = "CANCELLED")
    cANCELLED("CANCELLED");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: Any?): kotlin.String? = if (data is OrderListStatusEnum) "$data" else null

        /**
         * Returns a valid [OrderListStatusEnum] for [data], null otherwise.
         */
        fun decode(data: Any?): OrderListStatusEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

