/**
 * Nucoro API
 *
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Status2efEnum

import com.squareup.moshi.Json

/**
 * A ModelSerializer that takes additional arguments for \"fields\", \"omit\" and \"expand\" in order to control which fields are displayed, and whether to replace simple values with complex, nested serializations
 *
 * @param uuid 
 * @param name 
 * @param portfolioType 
 * @param riskLevel 
 * @param timeHorizon 
 * @param status 
 * @param balance 
 * @param invested 
 * @param created 
 * @param client 
 * @param currency 
 * @param advisor 
 * @param adviceEngine 
 */

data class PortfolioList (

    @Json(name = "uuid")
    val uuid: java.util.UUID,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "portfolio_type")
    val portfolioType: kotlin.String,

    @Json(name = "risk_level")
    val riskLevel: kotlin.Int,

    @Json(name = "time_horizon")
    val timeHorizon: kotlin.Int,

    @Json(name = "status")
    val status: Status2efEnum,

    @Json(name = "balance")
    val balance: kotlin.Double,

    @Json(name = "invested")
    val invested: kotlin.Double,

    @Json(name = "created")
    val created: java.time.OffsetDateTime,

    @Json(name = "client")
    val client: kotlin.String? = null,

    @Json(name = "currency")
    val currency: kotlin.String? = null,

    @Json(name = "advisor")
    val advisor: kotlin.String? = null,

    @Json(name = "advice_engine")
    val adviceEngine: kotlin.String? = null

)

