/**
 * Nucoro API
 *
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Category

import com.squareup.moshi.Json

/**
 * 
 *
 * @param uuid 
 * @param code 
 * @param categories 
 */

data class PresetCategoryGroup (

    @Json(name = "uuid")
    val uuid: java.util.UUID,

    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "categories")
    val categories: kotlin.collections.List<Category>

)

