/**
 * Nucoro API
 *
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OneOfLessThanResultEnumCommaBlankEnumGreaterThan
import org.openapitools.client.models.StatusBd7Enum
import org.openapitools.client.models.VerificationDocumentCreate
import org.openapitools.client.models.VerifyTypeEnum

import com.squareup.moshi.Json

/**
 * 
 *
 * @param uuid 
 * @param verifyType 
 * @param created 
 * @param updated 
 * @param verificationDocuments 
 * @param status 
 * @param result 
 */

data class VerificationWithType (

    @Json(name = "uuid")
    val uuid: java.util.UUID,

    @Json(name = "verify_type")
    val verifyType: VerifyTypeEnum,

    @Json(name = "created")
    val created: java.time.OffsetDateTime,

    @Json(name = "updated")
    val updated: java.time.OffsetDateTime,

    @Json(name = "verification_documents")
    val verificationDocuments: kotlin.collections.List<VerificationDocumentCreate>?,

    @Json(name = "status")
    val status: StatusBd7Enum? = null,

    @Json(name = "result")
    val result: OneOfLessThanResultEnumCommaBlankEnumGreaterThan? = null

)

