/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export enum AssetTypeEnum {
    Etf = <any> 'ETF',
    MutualFund = <any> 'MUTUAL_FUND',
    Stock = <any> 'STOCK'
}
