/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface DepositDetail {
    uuid: string;

    portfolio: string;

    amount: number;

    provider: string;

    reference: string;

    status?: models.StatusB6aEnum;

    /**
     * Cancelled reason
     */
    reason?: string;

    completed?: string;

    deposit_type?: models.DepositTypeEnum;

    transacted_at?: string;

    /**
     * Additional deposit attributes for the specific portal
     */
    extra_data?: { [key: string]: any; };

}
