/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PatchedGoal {
    uuid?: string;

    name?: string;

    portfolio?: string;

    /**
     * Desired amount needed to fulfill the goal
     */
    goal_amount?: number;

    /**
     * Due date to reach the goal.
     */
    deadline?: string;

    /**
     * Initial deposit amount to start from. No sense to start by 0
     */
    initial_amount?: number;

    recurring_amount?: number;

    risk_level?: number;

    created?: string;

}
