/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PortfolioPerformancePositions {
    valuation_datetime: string;

    last_update: string;

    asset: string;

    shares: number;

    price: number;

    currency: string;

    weight?: number;

    fx_rate_account?: number;

    asset_currency_value?: number;

    value: number;

    position_return: number;

    unrealised_pl: number;

    realised_pl: number;

    earnings: number;

    avg_entry_price: number;

    daily_pl: number;

}
