/**
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Tos {
    uuid: string;

    version: string;

    content: string;

    published?: string;

    previous_tos_uuid: string;

    next_tos_uuid: string;

}
