export * from './AddressApi';
import { AddressApi } from './AddressApi';
export * from './AnalyticsApi';
import { AnalyticsApi } from './AnalyticsApi';
export * from './ApiApi';
import { ApiApi } from './ApiApi';
export * from './ApplicationApi';
import { ApplicationApi } from './ApplicationApi';
export * from './AuthApi';
import { AuthApi } from './AuthApi';
export * from './BankAccountApi';
import { BankAccountApi } from './BankAccountApi';
export * from './ClientApi';
import { ClientApi } from './ClientApi';
export * from './DocumentApi';
import { DocumentApi } from './DocumentApi';
export * from './KYCApi';
import { KYCApi } from './KYCApi';
export * from './NationlityApi';
import { NationlityApi } from './NationlityApi';
export * from './RelationShipManagerApi';
import { RelationShipManagerApi } from './RelationShipManagerApi';
export * from './RiskAssessmentApi';
import { RiskAssessmentApi } from './RiskAssessmentApi';
export * from './TaxInformationApi';
import { TaxInformationApi } from './TaxInformationApi';
export const APIS = [AddressApi, AnalyticsApi, ApiApi, ApplicationApi, AuthApi, BankAccountApi, ClientApi, DocumentApi, KYCApi, NationlityApi, RelationShipManagerApi, RiskAssessmentApi, TaxInformationApi];
