/*
Nucoro API

No description

API version: 4.175.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// NationalityUpdate A ModelSerializer that takes additional arguments for \"fields\", \"omit\" and \"expand\" in order to control which fields are displayed, and whether to replace simple values with complex, nested serializations
type NationalityUpdate struct {
	Country string `json:"country"`
	DocumentNumber NullableString `json:"document_number,omitempty"`
	DocumentType *string `json:"document_type,omitempty"`
}

// NewNationalityUpdate instantiates a new NationalityUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNationalityUpdate(country string) *NationalityUpdate {
	this := NationalityUpdate{}
	this.Country = country
	return &this
}

// NewNationalityUpdateWithDefaults instantiates a new NationalityUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNationalityUpdateWithDefaults() *NationalityUpdate {
	this := NationalityUpdate{}
	return &this
}

// GetCountry returns the Country field value
func (o *NationalityUpdate) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *NationalityUpdate) GetCountryOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *NationalityUpdate) SetCountry(v string) {
	o.Country = v
}

// GetDocumentNumber returns the DocumentNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NationalityUpdate) GetDocumentNumber() string {
	if o == nil || o.DocumentNumber.Get() == nil {
		var ret string
		return ret
	}
	return *o.DocumentNumber.Get()
}

// GetDocumentNumberOk returns a tuple with the DocumentNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NationalityUpdate) GetDocumentNumberOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.DocumentNumber.Get(), o.DocumentNumber.IsSet()
}

// HasDocumentNumber returns a boolean if a field has been set.
func (o *NationalityUpdate) HasDocumentNumber() bool {
	if o != nil && o.DocumentNumber.IsSet() {
		return true
	}

	return false
}

// SetDocumentNumber gets a reference to the given NullableString and assigns it to the DocumentNumber field.
func (o *NationalityUpdate) SetDocumentNumber(v string) {
	o.DocumentNumber.Set(&v)
}
// SetDocumentNumberNil sets the value for DocumentNumber to be an explicit nil
func (o *NationalityUpdate) SetDocumentNumberNil() {
	o.DocumentNumber.Set(nil)
}

// UnsetDocumentNumber ensures that no value is present for DocumentNumber, not even an explicit nil
func (o *NationalityUpdate) UnsetDocumentNumber() {
	o.DocumentNumber.Unset()
}

// GetDocumentType returns the DocumentType field value if set, zero value otherwise.
func (o *NationalityUpdate) GetDocumentType() string {
	if o == nil || o.DocumentType == nil {
		var ret string
		return ret
	}
	return *o.DocumentType
}

// GetDocumentTypeOk returns a tuple with the DocumentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NationalityUpdate) GetDocumentTypeOk() (*string, bool) {
	if o == nil || o.DocumentType == nil {
		return nil, false
	}
	return o.DocumentType, true
}

// HasDocumentType returns a boolean if a field has been set.
func (o *NationalityUpdate) HasDocumentType() bool {
	if o != nil && o.DocumentType != nil {
		return true
	}

	return false
}

// SetDocumentType gets a reference to the given string and assigns it to the DocumentType field.
func (o *NationalityUpdate) SetDocumentType(v string) {
	o.DocumentType = &v
}

func (o NationalityUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["country"] = o.Country
	}
	if o.DocumentNumber.IsSet() {
		toSerialize["document_number"] = o.DocumentNumber.Get()
	}
	if o.DocumentType != nil {
		toSerialize["document_type"] = o.DocumentType
	}
	return json.Marshal(toSerialize)
}

type NullableNationalityUpdate struct {
	value *NationalityUpdate
	isSet bool
}

func (v NullableNationalityUpdate) Get() *NationalityUpdate {
	return v.value
}

func (v *NullableNationalityUpdate) Set(val *NationalityUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableNationalityUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableNationalityUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNationalityUpdate(val *NationalityUpdate) *NullableNationalityUpdate {
	return &NullableNationalityUpdate{value: val, isSet: true}
}

func (v NullableNationalityUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNationalityUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


