/*
Nucoro API

No description

API version: 4.175.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// PortfolioPerformancePositions struct for PortfolioPerformancePositions
type PortfolioPerformancePositions struct {
	ValuationDatetime time.Time `json:"valuation_datetime"`
	LastUpdate time.Time `json:"last_update"`
	Asset string `json:"asset"`
	Shares float64 `json:"shares"`
	Price float64 `json:"price"`
	Currency string `json:"currency"`
	Weight *float64 `json:"weight,omitempty"`
	FxRateAccount *float64 `json:"fx_rate_account,omitempty"`
	AssetCurrencyValue *float64 `json:"asset_currency_value,omitempty"`
	Value float64 `json:"value"`
	PositionReturn float64 `json:"position_return"`
	UnrealisedPl float64 `json:"unrealised_pl"`
	RealisedPl float64 `json:"realised_pl"`
	Earnings float64 `json:"earnings"`
	AvgEntryPrice float64 `json:"avg_entry_price"`
	DailyPl float64 `json:"daily_pl"`
}

// NewPortfolioPerformancePositions instantiates a new PortfolioPerformancePositions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPortfolioPerformancePositions(valuationDatetime time.Time, lastUpdate time.Time, asset string, shares float64, price float64, currency string, value float64, positionReturn float64, unrealisedPl float64, realisedPl float64, earnings float64, avgEntryPrice float64, dailyPl float64) *PortfolioPerformancePositions {
	this := PortfolioPerformancePositions{}
	this.ValuationDatetime = valuationDatetime
	this.LastUpdate = lastUpdate
	this.Asset = asset
	this.Shares = shares
	this.Price = price
	this.Currency = currency
	this.Value = value
	this.PositionReturn = positionReturn
	this.UnrealisedPl = unrealisedPl
	this.RealisedPl = realisedPl
	this.Earnings = earnings
	this.AvgEntryPrice = avgEntryPrice
	this.DailyPl = dailyPl
	return &this
}

// NewPortfolioPerformancePositionsWithDefaults instantiates a new PortfolioPerformancePositions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPortfolioPerformancePositionsWithDefaults() *PortfolioPerformancePositions {
	this := PortfolioPerformancePositions{}
	return &this
}

// GetValuationDatetime returns the ValuationDatetime field value
func (o *PortfolioPerformancePositions) GetValuationDatetime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ValuationDatetime
}

// GetValuationDatetimeOk returns a tuple with the ValuationDatetime field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetValuationDatetimeOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ValuationDatetime, true
}

// SetValuationDatetime sets field value
func (o *PortfolioPerformancePositions) SetValuationDatetime(v time.Time) {
	o.ValuationDatetime = v
}

// GetLastUpdate returns the LastUpdate field value
func (o *PortfolioPerformancePositions) GetLastUpdate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUpdate
}

// GetLastUpdateOk returns a tuple with the LastUpdate field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetLastUpdateOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastUpdate, true
}

// SetLastUpdate sets field value
func (o *PortfolioPerformancePositions) SetLastUpdate(v time.Time) {
	o.LastUpdate = v
}

// GetAsset returns the Asset field value
func (o *PortfolioPerformancePositions) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetAssetOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *PortfolioPerformancePositions) SetAsset(v string) {
	o.Asset = v
}

// GetShares returns the Shares field value
func (o *PortfolioPerformancePositions) GetShares() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Shares
}

// GetSharesOk returns a tuple with the Shares field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetSharesOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Shares, true
}

// SetShares sets field value
func (o *PortfolioPerformancePositions) SetShares(v float64) {
	o.Shares = v
}

// GetPrice returns the Price field value
func (o *PortfolioPerformancePositions) GetPrice() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetPriceOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *PortfolioPerformancePositions) SetPrice(v float64) {
	o.Price = v
}

// GetCurrency returns the Currency field value
func (o *PortfolioPerformancePositions) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetCurrencyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PortfolioPerformancePositions) SetCurrency(v string) {
	o.Currency = v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *PortfolioPerformancePositions) GetWeight() float64 {
	if o == nil || o.Weight == nil {
		var ret float64
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetWeightOk() (*float64, bool) {
	if o == nil || o.Weight == nil {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *PortfolioPerformancePositions) HasWeight() bool {
	if o != nil && o.Weight != nil {
		return true
	}

	return false
}

// SetWeight gets a reference to the given float64 and assigns it to the Weight field.
func (o *PortfolioPerformancePositions) SetWeight(v float64) {
	o.Weight = &v
}

// GetFxRateAccount returns the FxRateAccount field value if set, zero value otherwise.
func (o *PortfolioPerformancePositions) GetFxRateAccount() float64 {
	if o == nil || o.FxRateAccount == nil {
		var ret float64
		return ret
	}
	return *o.FxRateAccount
}

// GetFxRateAccountOk returns a tuple with the FxRateAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetFxRateAccountOk() (*float64, bool) {
	if o == nil || o.FxRateAccount == nil {
		return nil, false
	}
	return o.FxRateAccount, true
}

// HasFxRateAccount returns a boolean if a field has been set.
func (o *PortfolioPerformancePositions) HasFxRateAccount() bool {
	if o != nil && o.FxRateAccount != nil {
		return true
	}

	return false
}

// SetFxRateAccount gets a reference to the given float64 and assigns it to the FxRateAccount field.
func (o *PortfolioPerformancePositions) SetFxRateAccount(v float64) {
	o.FxRateAccount = &v
}

// GetAssetCurrencyValue returns the AssetCurrencyValue field value if set, zero value otherwise.
func (o *PortfolioPerformancePositions) GetAssetCurrencyValue() float64 {
	if o == nil || o.AssetCurrencyValue == nil {
		var ret float64
		return ret
	}
	return *o.AssetCurrencyValue
}

// GetAssetCurrencyValueOk returns a tuple with the AssetCurrencyValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetAssetCurrencyValueOk() (*float64, bool) {
	if o == nil || o.AssetCurrencyValue == nil {
		return nil, false
	}
	return o.AssetCurrencyValue, true
}

// HasAssetCurrencyValue returns a boolean if a field has been set.
func (o *PortfolioPerformancePositions) HasAssetCurrencyValue() bool {
	if o != nil && o.AssetCurrencyValue != nil {
		return true
	}

	return false
}

// SetAssetCurrencyValue gets a reference to the given float64 and assigns it to the AssetCurrencyValue field.
func (o *PortfolioPerformancePositions) SetAssetCurrencyValue(v float64) {
	o.AssetCurrencyValue = &v
}

// GetValue returns the Value field value
func (o *PortfolioPerformancePositions) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetValueOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *PortfolioPerformancePositions) SetValue(v float64) {
	o.Value = v
}

// GetPositionReturn returns the PositionReturn field value
func (o *PortfolioPerformancePositions) GetPositionReturn() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.PositionReturn
}

// GetPositionReturnOk returns a tuple with the PositionReturn field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetPositionReturnOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PositionReturn, true
}

// SetPositionReturn sets field value
func (o *PortfolioPerformancePositions) SetPositionReturn(v float64) {
	o.PositionReturn = v
}

// GetUnrealisedPl returns the UnrealisedPl field value
func (o *PortfolioPerformancePositions) GetUnrealisedPl() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.UnrealisedPl
}

// GetUnrealisedPlOk returns a tuple with the UnrealisedPl field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetUnrealisedPlOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UnrealisedPl, true
}

// SetUnrealisedPl sets field value
func (o *PortfolioPerformancePositions) SetUnrealisedPl(v float64) {
	o.UnrealisedPl = v
}

// GetRealisedPl returns the RealisedPl field value
func (o *PortfolioPerformancePositions) GetRealisedPl() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.RealisedPl
}

// GetRealisedPlOk returns a tuple with the RealisedPl field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetRealisedPlOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RealisedPl, true
}

// SetRealisedPl sets field value
func (o *PortfolioPerformancePositions) SetRealisedPl(v float64) {
	o.RealisedPl = v
}

// GetEarnings returns the Earnings field value
func (o *PortfolioPerformancePositions) GetEarnings() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Earnings
}

// GetEarningsOk returns a tuple with the Earnings field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetEarningsOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Earnings, true
}

// SetEarnings sets field value
func (o *PortfolioPerformancePositions) SetEarnings(v float64) {
	o.Earnings = v
}

// GetAvgEntryPrice returns the AvgEntryPrice field value
func (o *PortfolioPerformancePositions) GetAvgEntryPrice() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.AvgEntryPrice
}

// GetAvgEntryPriceOk returns a tuple with the AvgEntryPrice field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetAvgEntryPriceOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AvgEntryPrice, true
}

// SetAvgEntryPrice sets field value
func (o *PortfolioPerformancePositions) SetAvgEntryPrice(v float64) {
	o.AvgEntryPrice = v
}

// GetDailyPl returns the DailyPl field value
func (o *PortfolioPerformancePositions) GetDailyPl() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.DailyPl
}

// GetDailyPlOk returns a tuple with the DailyPl field value
// and a boolean to check if the value has been set.
func (o *PortfolioPerformancePositions) GetDailyPlOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DailyPl, true
}

// SetDailyPl sets field value
func (o *PortfolioPerformancePositions) SetDailyPl(v float64) {
	o.DailyPl = v
}

func (o PortfolioPerformancePositions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["valuation_datetime"] = o.ValuationDatetime
	}
	if true {
		toSerialize["last_update"] = o.LastUpdate
	}
	if true {
		toSerialize["asset"] = o.Asset
	}
	if true {
		toSerialize["shares"] = o.Shares
	}
	if true {
		toSerialize["price"] = o.Price
	}
	if true {
		toSerialize["currency"] = o.Currency
	}
	if o.Weight != nil {
		toSerialize["weight"] = o.Weight
	}
	if o.FxRateAccount != nil {
		toSerialize["fx_rate_account"] = o.FxRateAccount
	}
	if o.AssetCurrencyValue != nil {
		toSerialize["asset_currency_value"] = o.AssetCurrencyValue
	}
	if true {
		toSerialize["value"] = o.Value
	}
	if true {
		toSerialize["position_return"] = o.PositionReturn
	}
	if true {
		toSerialize["unrealised_pl"] = o.UnrealisedPl
	}
	if true {
		toSerialize["realised_pl"] = o.RealisedPl
	}
	if true {
		toSerialize["earnings"] = o.Earnings
	}
	if true {
		toSerialize["avg_entry_price"] = o.AvgEntryPrice
	}
	if true {
		toSerialize["daily_pl"] = o.DailyPl
	}
	return json.Marshal(toSerialize)
}

type NullablePortfolioPerformancePositions struct {
	value *PortfolioPerformancePositions
	isSet bool
}

func (v NullablePortfolioPerformancePositions) Get() *PortfolioPerformancePositions {
	return v.value
}

func (v *NullablePortfolioPerformancePositions) Set(val *PortfolioPerformancePositions) {
	v.value = val
	v.isSet = true
}

func (v NullablePortfolioPerformancePositions) IsSet() bool {
	return v.isSet
}

func (v *NullablePortfolioPerformancePositions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePortfolioPerformancePositions(val *PortfolioPerformancePositions) *NullablePortfolioPerformancePositions {
	return &NullablePortfolioPerformancePositions{value: val, isSet: true}
}

func (v NullablePortfolioPerformancePositions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePortfolioPerformancePositions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


