/*
Nucoro API

No description

API version: 4.175.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PortfolioTypeRestrictions struct for PortfolioTypeRestrictions
type PortfolioTypeRestrictions struct {
	PortfolioType string `json:"portfolio_type"`
	Key string `json:"key"`
}

// NewPortfolioTypeRestrictions instantiates a new PortfolioTypeRestrictions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPortfolioTypeRestrictions(portfolioType string, key string) *PortfolioTypeRestrictions {
	this := PortfolioTypeRestrictions{}
	this.PortfolioType = portfolioType
	this.Key = key
	return &this
}

// NewPortfolioTypeRestrictionsWithDefaults instantiates a new PortfolioTypeRestrictions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPortfolioTypeRestrictionsWithDefaults() *PortfolioTypeRestrictions {
	this := PortfolioTypeRestrictions{}
	return &this
}

// GetPortfolioType returns the PortfolioType field value
func (o *PortfolioTypeRestrictions) GetPortfolioType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PortfolioType
}

// GetPortfolioTypeOk returns a tuple with the PortfolioType field value
// and a boolean to check if the value has been set.
func (o *PortfolioTypeRestrictions) GetPortfolioTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PortfolioType, true
}

// SetPortfolioType sets field value
func (o *PortfolioTypeRestrictions) SetPortfolioType(v string) {
	o.PortfolioType = v
}

// GetKey returns the Key field value
func (o *PortfolioTypeRestrictions) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PortfolioTypeRestrictions) GetKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PortfolioTypeRestrictions) SetKey(v string) {
	o.Key = v
}

func (o PortfolioTypeRestrictions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["portfolio_type"] = o.PortfolioType
	}
	if true {
		toSerialize["key"] = o.Key
	}
	return json.Marshal(toSerialize)
}

type NullablePortfolioTypeRestrictions struct {
	value *PortfolioTypeRestrictions
	isSet bool
}

func (v NullablePortfolioTypeRestrictions) Get() *PortfolioTypeRestrictions {
	return v.value
}

func (v *NullablePortfolioTypeRestrictions) Set(val *PortfolioTypeRestrictions) {
	v.value = val
	v.isSet = true
}

func (v NullablePortfolioTypeRestrictions) IsSet() bool {
	return v.isSet
}

func (v *NullablePortfolioTypeRestrictions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePortfolioTypeRestrictions(val *PortfolioTypeRestrictions) *NullablePortfolioTypeRestrictions {
	return &NullablePortfolioTypeRestrictions{value: val, isSet: true}
}

func (v NullablePortfolioTypeRestrictions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePortfolioTypeRestrictions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


