/*
Nucoro API

No description

API version: 4.175.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ActivityTypeEnum the model 'ActivityTypeEnum'
type ActivityTypeEnum string

// List of ActivityTypeEnum
const (
	CREATED ActivityTypeEnum = "CREATED"
	UPDATED ActivityTypeEnum = "UPDATED"
	DELETED ActivityTypeEnum = "DELETED"
)

var allowedActivityTypeEnumEnumValues = []ActivityTypeEnum{
	"CREATED",
	"UPDATED",
	"DELETED",
}

func (v *ActivityTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ActivityTypeEnum(value)
	for _, existing := range allowedActivityTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ActivityTypeEnum", value)
}

// NewActivityTypeEnumFromValue returns a pointer to a valid ActivityTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewActivityTypeEnumFromValue(v string) (*ActivityTypeEnum, error) {
	ev := ActivityTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ActivityTypeEnum: valid values are %v", v, allowedActivityTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ActivityTypeEnum) IsValid() bool {
	for _, existing := range allowedActivityTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ActivityTypeEnum value
func (v ActivityTypeEnum) Ptr() *ActivityTypeEnum {
	return &v
}

type NullableActivityTypeEnum struct {
	value *ActivityTypeEnum
	isSet bool
}

func (v NullableActivityTypeEnum) Get() *ActivityTypeEnum {
	return v.value
}

func (v *NullableActivityTypeEnum) Set(val *ActivityTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableActivityTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableActivityTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActivityTypeEnum(val *ActivityTypeEnum) *NullableActivityTypeEnum {
	return &NullableActivityTypeEnum{value: val, isSet: true}
}

func (v NullableActivityTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivityTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

