//
// GenderEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GenderEnum: String, Codable, CaseIterable {
    case m = "M"
    case f = "F"
    case u = "U"
}
