//
// PatchedAssessment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedAssessment: Codable, Hashable {

    public var uuid: UUID?
    public var completed: Date?
    public var choices: [RiskChoiceQuestionCode]?
    public var status: AssessmentStatusEnum?
    public var riskLevel: Int?
    public var created: Date?

    public init(uuid: UUID? = nil, completed: Date? = nil, choices: [RiskChoiceQuestionCode]? = nil, status: AssessmentStatusEnum? = nil, riskLevel: Int? = nil, created: Date? = nil) {
        self.uuid = uuid
        self.completed = completed
        self.choices = choices
        self.status = status
        self.riskLevel = riskLevel
        self.created = created
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case completed
        case choices
        case status
        case riskLevel = "risk_level"
        case created
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(uuid, forKey: .uuid)
        try container.encodeIfPresent(completed, forKey: .completed)
        try container.encodeIfPresent(choices, forKey: .choices)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(riskLevel, forKey: .riskLevel)
        try container.encodeIfPresent(created, forKey: .created)
    }
}

