//
// VerifyTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum VerifyTypeEnum: String, Codable, CaseIterable {
    case identity = "IDENTITY"
    case banking = "BANKING"
}
