//
// DepositList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DepositList: Codable, Hashable {

    public var uuid: UUID
    public var amount: Double
    public var reference: String
    public var status: StatusB6aEnum
    public var depositType: DepositTypeEnum
    public var completed: Date
    public var transactedAt: Date
    /** Additional deposit attributes for the specific portal */
    public var extraData: [String: AnyCodable]

    public init(uuid: UUID, amount: Double, reference: String, status: StatusB6aEnum, depositType: DepositTypeEnum, completed: Date, transactedAt: Date, extraData: [String: AnyCodable]) {
        self.uuid = uuid
        self.amount = amount
        self.reference = reference
        self.status = status
        self.depositType = depositType
        self.completed = completed
        self.transactedAt = transactedAt
        self.extraData = extraData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case amount
        case reference
        case status
        case depositType = "deposit_type"
        case completed
        case transactedAt = "transacted_at"
        case extraData = "extra_data"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(amount, forKey: .amount)
        try container.encode(reference, forKey: .reference)
        try container.encode(status, forKey: .status)
        try container.encode(depositType, forKey: .depositType)
        try container.encode(completed, forKey: .completed)
        try container.encode(transactedAt, forKey: .transactedAt)
        try container.encode(extraData, forKey: .extraData)
    }
}

