//
// PatchedAddressUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedAddressUpdate: Codable, Hashable {

    public var uuid: UUID?
    public var line1: String?
    public var line2: String?
    public var postcode: String?
    public var locality: String?
    public var country: String?
    public var region: String?

    public init(uuid: UUID? = nil, line1: String? = nil, line2: String? = nil, postcode: String? = nil, locality: String? = nil, country: String? = nil, region: String? = nil) {
        self.uuid = uuid
        self.line1 = line1
        self.line2 = line2
        self.postcode = postcode
        self.locality = locality
        self.country = country
        self.region = region
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case line1
        case line2
        case postcode
        case locality
        case country
        case region
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(uuid, forKey: .uuid)
        try container.encodeIfPresent(line1, forKey: .line1)
        try container.encodeIfPresent(line2, forKey: .line2)
        try container.encodeIfPresent(postcode, forKey: .postcode)
        try container.encodeIfPresent(locality, forKey: .locality)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(region, forKey: .region)
    }
}

