//
// PortalSettingValueList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PortalSettingValueList: Codable, Hashable {

    public var id: Int
    public var uuid: UUID
    public var created: Date
    public var updated: Date
    public var value: String
    public var portal: Int
    public var key: Int

    public init(id: Int, uuid: UUID, created: Date, updated: Date, value: String, portal: Int, key: Int) {
        self.id = id
        self.uuid = uuid
        self.created = created
        self.updated = updated
        self.value = value
        self.portal = portal
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case uuid
        case created
        case updated
        case value
        case portal
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(created, forKey: .created)
        try container.encode(updated, forKey: .updated)
        try container.encode(value, forKey: .value)
        try container.encode(portal, forKey: .portal)
        try container.encode(key, forKey: .key)
    }
}

