/*
 * Nucoro API
 * No description
 *
 * The version of the OpenAPI document: 4.175.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ClientEmbedRanking;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ClientRanking
 */
public class ClientRankingTest {
    private final ClientRanking model = new ClientRanking();

    /**
     * Model tests for ClientRanking
     */
    @Test
    public void testClientRanking() {
        // TODO: test ClientRanking
    }

    /**
     * Test the property 'topPerforming'
     */
    @Test
    public void topPerformingTest() {
        // TODO: test topPerforming
    }

    /**
     * Test the property 'bottomPerforming'
     */
    @Test
    public void bottomPerformingTest() {
        // TODO: test bottomPerforming
    }

}
