=begin
Nucoro API

No description

The version of the OpenAPI document: 4.175.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class AuthController < ApplicationController

  def auth_get_onboarding_token
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def auth_impersonation_token
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def auth_login
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def auth_resfresh_jwt_token
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_change_password
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_request_password_reset
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_set_password
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
