=begin
Nucoro API

No description

The version of the OpenAPI document: 4.175.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class NationlityController < ApplicationController

  def client_nationality_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def client_nationlities_list
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def client_nationlity_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def client_nationlity_partial_update
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def client_nationlity_retrieve
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def client_nationlity_update
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
