"""
    Nucoro API v2

    No description  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.status260_enum import Status260Enum


class TestStatus260Enum(unittest.TestCase):
    """Status260Enum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatus260Enum(self):
        """Test Status260Enum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Status260Enum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
