"""
    Nucoro API v2

    No description  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.investor_fee import InvestorFee


class TestInvestorFee(unittest.TestCase):
    """InvestorFee unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvestorFee(self):
        """Test InvestorFee"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvestorFee()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
