"""
    Nucoro API v2

    No description  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.preset_category_group import PresetCategoryGroup
globals()['PresetCategoryGroup'] = PresetCategoryGroup
from openapi_client.model.paginated_preset_category_group_list import PaginatedPresetCategoryGroupList


class TestPaginatedPresetCategoryGroupList(unittest.TestCase):
    """PaginatedPresetCategoryGroupList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedPresetCategoryGroupList(self):
        """Test PaginatedPresetCategoryGroupList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedPresetCategoryGroupList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
