"""
    Nucoro API v2

    No description  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.bank_account_list import BankAccountList
globals()['BankAccountList'] = BankAccountList
from openapi_client.model.paginated_bank_account_list_list import PaginatedBankAccountListList


class TestPaginatedBankAccountListList(unittest.TestCase):
    """PaginatedBankAccountListList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedBankAccountListList(self):
        """Test PaginatedBankAccountListList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedBankAccountListList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
